### ISSUE TITLE
Unified Goldberg settings

### ISSUE THREAD

**Issue by Adephx** [BigBoiCJ/SteamAutoCracker#58] opened 2024-04-20 17:29 UTC
Would be nice if the interface included unified Goldberg settings for custom options, such as default save location, username, LAN mode, etc.

**Comment by BigBoiCJ** [comment] 2024-04-27 12:18
Thanks for the suggestion! I believe this is a duplicate of #55 

I'll take your suggestion into account though, as it seems you're talking about the settings in `%appdata%\Goldberg SteamEmu Saves\settings\`. I'll try to add an option to either use the default config, and allows to easily modify it, as well as an option to use custom settings (which will be in steam_settings in the game folder)

**Closed by BigBoiCJ** 2024-04-27 12:18 UTC
Labels: duplicate, enhancement

**Comment by Adephx** [comment] 2024-04-30 07:44
If I may elaborate. I was already working on a similar project before I realized that you were already working on it. But instead of the program acting like a crack patcher, it was acting as a centralised hub-launcher for cracked steam games. For example, you run the launcher and setup the default settings, for example your username, language, etc. then you add the game to the library, it cracks it, as your patcher does and copies the default settings. If you change the username, it overwrites the settings for all of the games in your library. This is important, because we use Goldberg to play games either through LAN or ZeroTier network and setting up usernames, etc. is a major pain in the ass for the people with no technical know how.

On a related note, it would be an absolute god-tier, if we integrated ZeroTier directly node into the launcher, as it's open source (https://github.com/zerotier/ZeroTierOne) and set the Broadcast directly to it:

`
Custom Broadcast ips:
If you want to set custom ips (or domains) which the emulator will send broadcast packets to, make a list of them, one on each line in: Goldberg SteamEmu Saves\settings\custom_broadcasts.txt
If the custom ips/domains are specific for one game only you can put the custom_broadcasts.txt in the steam_settings\ folder.
An example is provided in steam_settings.EXAMPLE\custom_broadcasts.EXAMPLE.txt
`

**Comment by BigBoiCJ** [comment] 2024-04-30 16:47
Seems like an interesting project! Unfortunately it seems a lot of work to integrate and I have 0 knowledge about ZeroTier.

You can probably put a `custom_broadcasts.txt` file in `%appdata%\Goldberg SteamEmu Saves\settings\` though, and it should apply to all games that are cracked with Goldberg, as if I understand correctly, Goldberg's emu will use all the cfg files in this location, and then all the ones in the game's location.

Overwriting settings & all should be needed because of that. You can simply edit the files in `%appdata%\Goldberg SteamEmu Saves\settings\`.

I can only motivate you to work on your project if you have the time :)
